version: "3"
services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    depends_on:
      - redis
    environment:
      - PORT=8080
      - REDIS_HOST=redis
  
#  collector:
#    build: ./collector
#    links:
#      - redis
#    environment:
#      - HZ=30

  redis:
    image: redis
