version: "3"
services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 60s
      timeout: 10s
      retries: 3


  backend:
    build: ./backend
    depends_on:
      - redis
    environment:
      - PORT=8080
      - REDIS_HOST=redis

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/"]
      interval: 60s
      timeout: 10s
      retries: 3
  
#  collector:
#    build: ./collector
#    links:
#      - redis
#    environment:
#      - HZ=30

  redis:
    image: redis
